#!/bin/bash
#
# Perform necessary push-jobs-client setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
INSTALLER_DIR=/opt/opscode-push-jobs-client

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Ensure all files/directories in $INSTALLER_DIR are owned by root. This
# has been fixed on new installs but upgrades from old installs need to
# be manually fixed.
chown -Rh 0:0 $INSTALLER_DIR

echo "Thank you for installing Chef Push Client!"

exit 0
